
							###Find the Difference###

# Given two strings s and t which consist of only lowercase letters.
# String t is generated by random shuffling string s and then add one more letter at a random position.
# Find the letter that was added in t.
# Example:
# Input:
# s = "abcd", t = "abcde"
# Output: e
# Explanation:
# 'e' is the letter that was added.

class Solution(object):
    def findTheDifference(self, s, t):
        """
        :type s: str
        :type t: str
        :rtype: str
        """
        s = list(s)
        t = list(t)
        for i in s:
            t.remove(i)
        return t[0]    

class Solution(object):
    def findTheDifference(self, s, t):
        """
        :type s: str
        :type t: str
        :rtype: str
        """
        result1 = 0
        result2 = 0
        for i in range(len(s)):
			result1 += ord(s[i])   #ASCII
        for i in range(len(t)):
			result2 += ord(t[i])
        return chr(result2-result1)
        

